# Generated by Django 3.2.6 on 2021-08-04 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodrapp', '0005_auto_20210804_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
