# Generated by Django 3.2.6 on 2021-08-06 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodrapp', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
